services:
  database:
    image: mysql:latest
    container_name: wisely_database
    environment:
      APP_PORT: 3000
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - test_enviroment

  backend:
    build: ./backend
    container_name: wisely_backend
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      DB_HOST: database
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      DB_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_DIALECT: mysql
    networks:
      - test_enviroment

  frontend:
    build: ./frontend
    container_name: wisely_frontend
    depends_on:
      - backend
    ports:
      - "4000:80"
    environment:
      VUE_APP_API_URL: http://backend:3000
    networks:
      - test_enviroment

volumes:
  mysql_data:

networks:
  test_enviroment:
    driver: bridge